spring:
  application.name: java-dop-example
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: pg
    password: pg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop